import FWCore.ParameterSet.Config as cms

from Configuration.Generator.PythiaUEZ2Settings_cfi import *

generator = cms.EDFilter("Pythia6GeneratorFilter",
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    maxEventsToPrint = cms.untracked.int32(0),
    pythiaPylistVerbosity = cms.untracked.int32(1),
    filterEfficiency = cms.untracked.double(1.0),
    crossSection = cms.untracked.double(55000000000.),
    comEnergy = cms.double(13000.0),
    PythiaParameters = cms.PSet(
    pythiaUESettingsBlock,
# set proccess to be simulated
    processParameters = cms.vstring(
            'MSEL=0             ! User defined processes', 
            'MSUB(121)=1        ! gg to ttH', 
            'MSUB(122)=1        ! qq to ttH', 
            'PMAS(25,1)= 125.   ! m_h',
            'PMAS(6,1)= 172.6   ! mass of top quark',
            'PMAS(23,1)= 91.187 ! mass of Z',
            'PMAS(24,1)= 80.39  ! mass of W',

# Higgs (h0) decay channels
            'MDME(210,1)=0      ! d               dbar',
            'MDME(211,1)=0      ! u               ubar',
            'MDME(212,1)=0      ! s               sbar',
            'MDME(213,1)=0      ! c               cbar',
            'MDME(214,1)=0      ! b               bbar',
            'MDME(215,1)=0      ! t               tbar',
            'MDME(216,1)=0      ! bp              bp bar',
            'MDME(217,1)=0      ! tp              tp bar',
            'MDME(218,1)=0      ! e-              e+',
            'MDME(219,1)=1      ! mu-             mu+',
            'MDME(220,1)=0      ! tau-            tau+',
            'MDME(221,1)=0      ! taup -           taup +',
            'MDME(222,1)=0      ! g               g',      
            'MDME(223,1)=0      ! gamma           gamma',  
            'MDME(224,1)=0      ! gamma           Z0',     
            'MDME(225,1)=0      ! Z0              Z0',     
            'MDME(226,1)=0      ! W+              W-',     
            'MDME(227,1)=0      ! ~chi_10         ~chi_10',
            'MDME(228,1)=0      ! ~chi_20         ~chi_10',
            'MDME(229,1)=0      ! ~chi_20         ~chi_20',
            'MDME(230,1)=0      ! ~chi_30         ~chi_10',
            'MDME(231,1)=0      ! ~chi_30         ~chi_20',
            'MDME(232,1)=0      ! ~chi_30         ~chi_30',
            'MDME(233,1)=0      ! ~chi_40         ~chi_10',
            'MDME(234,1)=0      ! ~chi_40         ~chi_20',
            'MDME(235,1)=0      ! ~chi_40         ~chi_40',
            'MDME(237,1)=0      ! ~chi_1+         ~chi_1-',
            'MDME(238,1)=0      ! ~chi_1+         ~chi_2-',
            'MDME(239,1)=0      ! ~chi_2+         ~chi_1-',
            'MDME(240,1)=0      ! ~chi_2+         ~chi_2-',
            'MDME(241,1)=0      ! ~d_L            ~d_Lbar',
            'MDME(242,1)=0      ! ~d_R            ~d_Rbar',
            'MDME(243,1)=0      ! ~d_L            ~d_Rbar',
            'MDME(244,1)=0      ! ~d_Lbar         ~d_R',   
            'MDME(245,1)=0      ! ~u_L            ~u_Lbar',
            'MDME(246,1)=0      ! ~u_R            ~u_Rbar',
            'MDME(247,1)=0      ! ~u_L            ~u_Rbar',
            'MDME(248,1)=0      ! ~u_Lbar         ~u_R',   
            'MDME(249,1)=0      ! ~s_L            ~s_Lbar',
            'MDME(250,1)=0      ! ~s_R            ~s_Rbar',
            'MDME(251,1)=0      ! ~s_L            ~s_Rbar',
            'MDME(252,1)=0      ! ~s_Lbar         ~s_R',   
            'MDME(253,1)=0      ! ~c_L            ~c_Lbar',
            'MDME(254,1)=0      ! ~c_R            ~c_Rbar',
            'MDME(255,1)=0      ! ~c_L            ~c_Rbar',
            'MDME(256,1)=0      ! ~c_Lbar         ~c_R',   
            'MDME(257,1)=0      ! ~b_1            ~b_1bar',
            'MDME(258,1)=0      ! ~b_2            ~b_2bar',
            'MDME(259,1)=0      ! ~b_1            ~b_2bar',
            'MDME(260,1)=0      ! ~b_1bar         ~b_2',
            'MDME(261,1)=0      ! ~t_1            ~t_1bar',
            'MDME(262,1)=0      ! ~t_2            ~t_2bar',
            'MDME(263,1)=0      ! ~t_1            ~t_2bar',                                    
            'MDME(264,1)=0      ! ~t_1bar         ~t_2',   
            'MDME(265,1)=0      ! ~e_L-           ~e_L+',  
            'MDME(266,1)=0      ! ~e_R-           ~e_R+',  
            'MDME(267,1)=0      ! ~e_L-           ~e_R+',  
            'MDME(268,1)=0      ! ~e_L+           ~e_R-',  
            'MDME(269,1)=0      ! ~nu_eL          ~nu_eLbar',                                    
            'MDME(270,1)=0      ! ~nu_eR          ~nu_eRbar',                                    
            'MDME(271,1)=0      ! ~nu_eL          ~nu_eRbar',                                    
            'MDME(272,1)=0      ! ~nu_eLbar       ~nu_eR', 
            'MDME(273,1)=0      ! ~mu_L-          ~mu_L+', 
            'MDME(274,1)=0      ! ~mu_R-          ~mu_R+', 
            'MDME(275,1)=0      ! ~mu_L-          ~mu_R+', 
            'MDME(276,1)=0      ! ~mu_L+          ~mu_R-', 
            'MDME(277,1)=0      ! ~nu_muL         ~nu_muLbar',                                    
            'MDME(278,1)=0      ! ~nu_muR         ~nu_muRbar',                                    
            'MDME(279,1)=0      ! ~nu_muL         ~nu_muRbar',                                    
            'MDME(280,1)=0      ! ~nu_muLbar      ~nu_muR',
            'MDME(281,1)=0      ! ~tau_1-         ~tau_1+',
            'MDME(282,1)=0      ! ~tau_2-         ~tau_2+',
            'MDME(283,1)=0      ! ~tau_1-         ~tau_2+',
            'MDME(284,1)=0      ! ~tau_1+         ~tau_2-',
            'MDME(285,1)=0      ! ~nu_tauL        ~nu_tauLbar',
            'MDME(286,1)=0      ! ~nu_tauR        ~nu_tauRbar',                                    
            'MDME(287,1)=0      ! ~nu_tauL        ~nu_tauRbar',                                    
            'MDME(288,1)=0      ! ~nu_tauLbar     ~nu_tauR',                                    
        ),                            
        # This is a vector of ParameterSet names to be read, in this order
        parameterSets = cms.vstring('pythiaUESettings', 
            'processParameters')
    )
)
                             
